// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: host.proto

package host

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostAddInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"host" form:"host" uri:"host"
	Host string `protobuf:"bytes,2,opt,name=Host,proto3" json:"host" form:"host" uri:"host"`
	// @inject_tag: json:"username" form:"username" uri:"username"
	UserName string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"username" form:"username" uri:"username"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,4,opt,name=Password,proto3" json:"password" form:"password" uri:"password"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	Content string `protobuf:"bytes,5,opt,name=Content,proto3" json:"content" form:"content" uri:"content"`
	// @inject_tag: json:"type" form:"type" uri:"type"
	Type int64 `protobuf:"varint,6,opt,name=Type,proto3" json:"type" form:"type" uri:"type"`
}

func (x *HostAddInput) Reset() {
	*x = HostAddInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostAddInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAddInput) ProtoMessage() {}

func (x *HostAddInput) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAddInput.ProtoReflect.Descriptor instead.
func (*HostAddInput) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{0}
}

func (x *HostAddInput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostAddInput) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *HostAddInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *HostAddInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HostAddInput) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type HostDeleteInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" form:"id" uri:"id"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" form:"id" uri:"id"`
}

func (x *HostDeleteInput) Reset() {
	*x = HostDeleteInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostDeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDeleteInput) ProtoMessage() {}

func (x *HostDeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDeleteInput.ProtoReflect.Descriptor instead.
func (*HostDeleteInput) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{1}
}

func (x *HostDeleteInput) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type HostUpdateInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" form:"id" uri:"id"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" form:"id" uri:"id"`
	// @inject_tag: json:"host" form:"host" uri:"host"
	Host string `protobuf:"bytes,2,opt,name=Host,proto3" json:"host" form:"host" uri:"host"`
	// @inject_tag: json:"username" form:"username" uri:"username"
	UserName string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"username" form:"username" uri:"username"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,4,opt,name=Password,proto3" json:"password" form:"password" uri:"password"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	Content string `protobuf:"bytes,5,opt,name=Content,proto3" json:"content" form:"content" uri:"content"`
	// @inject_tag: json:"type" form:"type" uri:"type"
	Type int64 `protobuf:"varint,6,opt,name=Type,proto3" json:"type" form:"type" uri:"type"`
}

func (x *HostUpdateInput) Reset() {
	*x = HostUpdateInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostUpdateInput) ProtoMessage() {}

func (x *HostUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostUpdateInput.ProtoReflect.Descriptor instead.
func (*HostUpdateInput) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{2}
}

func (x *HostUpdateInput) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *HostUpdateInput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostUpdateInput) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *HostUpdateInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *HostUpdateInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HostUpdateInput) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" form:"info" uri:"info"
	ID int64 `protobuf:"varint,3,opt,name=ID,proto3" json:"id" form:"info" uri:"info"`
	// @inject_tag: json:"host" form:"host" uri:"host"
	Host string `protobuf:"bytes,4,opt,name=Host,proto3" json:"host" form:"host" uri:"host"`
	// @inject_tag: json:"username" form:"username" uri:"username"
	UserName string `protobuf:"bytes,5,opt,name=UserName,proto3" json:"username" form:"username" uri:"username"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,6,opt,name=Password,proto3" json:"password" form:"password" uri:"password"`
	// @inject_tag: json:"host_status" form:"host_status" uri:"host_status"
	HostStatus int64 `protobuf:"varint,7,opt,name=HostStatus,proto3" json:"host_status" form:"host_status" uri:"host_status"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	Content string `protobuf:"bytes,8,opt,name=Content,proto3" json:"content" form:"content" uri:"content"`
	// @inject_tag: json:"task_num" form:"task_num" uri:"task_num"
	TaskNum int64 `protobuf:"varint,9,opt,name=TaskNum,proto3" json:"task_num" form:"task_num" uri:"task_num"`
	// @inject_tag: json:"type" form:"type" uri:"type"
	Type int64 `protobuf:"varint,10,opt,name=Type,proto3" json:"type" form:"type" uri:"type"`
	// @inject_tag: json:"type" form:"type" uri:"create_at"
	CreateAt string `protobuf:"bytes,11,opt,name=CreateAt,proto3" json:"type" form:"type" uri:"create_at"`
	// @inject_tag: json:"type" form:"type" uri:"update_at"
	UpdateAt string `protobuf:"bytes,12,opt,name=UpdateAt,proto3" json:"type" form:"type" uri:"update_at"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{3}
}

func (x *ListItem) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ListItem) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ListItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ListItem) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ListItem) GetHostStatus() int64 {
	if x != nil {
		return x.HostStatus
	}
	return 0
}

func (x *ListItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListItem) GetTaskNum() int64 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *ListItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListItem) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *ListItem) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type HostOneMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"message" form:"message" uri:"message"
	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message" form:"message" uri:"message"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	OK bool `protobuf:"varint,2,opt,name=OK,proto3" json:"content" form:"content" uri:"content"`
}

func (x *HostOneMessage) Reset() {
	*x = HostOneMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostOneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOneMessage) ProtoMessage() {}

func (x *HostOneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOneMessage.ProtoReflect.Descriptor instead.
func (*HostOneMessage) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{4}
}

func (x *HostOneMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HostOneMessage) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

type HostListInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"info" form:"info" uri:"info"
	Info string `protobuf:"bytes,1,opt,name=Info,proto3" json:"info" form:"info" uri:"info"`
	// @inject_tag: json:"page_no" form:"page_no" uri:"page_no"
	PageNo int64 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"page_no" form:"page_no" uri:"page_no"`
	// @inject_tag: json:"page_size" form:"page_size" uri:"page_size"
	PageSize int64 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"page_size" form:"page_size" uri:"page_size"`
}

func (x *HostListInput) Reset() {
	*x = HostListInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostListInput) ProtoMessage() {}

func (x *HostListInput) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostListInput.ProtoReflect.Descriptor instead.
func (*HostListInput) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{5}
}

func (x *HostListInput) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HostListInput) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *HostListInput) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HostListOutPut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"total" form:"total" uri:"total"
	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"total" form:"total" uri:"total"`
	// @inject_tag: json:"list_item" form:"list_item" uri:"list_item"
	ListItem []*ListItem `protobuf:"bytes,2,rep,name=listItem,proto3" json:"list_item" form:"list_item" uri:"list_item"`
}

func (x *HostListOutPut) Reset() {
	*x = HostListOutPut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostListOutPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostListOutPut) ProtoMessage() {}

func (x *HostListOutPut) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostListOutPut.ProtoReflect.Descriptor instead.
func (*HostListOutPut) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{6}
}

func (x *HostListOutPut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *HostListOutPut) GetListItem() []*ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

var File_host_proto protoreflect.FileDescriptor

var file_host_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x48,
	0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x48, 0x6f, 0x73,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x73,
	0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x61, 0x73, 0x6b,
	0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22,
	0x3a, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f,
	0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x22, 0x57, 0x0a, 0x0d, 0x48,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x6a, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x42, 0x0a, 0x08,
	0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x32, 0xb3, 0x03, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x65, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x2c, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00,
	0x12, 0x6b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2d,
	0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2c, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2c, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4f, 0x6e,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2c, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75,
	0x74, 0x50, 0x75, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x68, 0x6f, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_host_proto_rawDescOnce sync.Once
	file_host_proto_rawDescData = file_host_proto_rawDesc
)

func file_host_proto_rawDescGZIP() []byte {
	file_host_proto_rawDescOnce.Do(func() {
		file_host_proto_rawDescData = protoimpl.X.CompressGZIP(file_host_proto_rawDescData)
	})
	return file_host_proto_rawDescData
}

var file_host_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_host_proto_goTypes = []interface{}{
	(*HostAddInput)(nil),    // 0: go.micro.service.backupAgent.HostAddInput
	(*HostDeleteInput)(nil), // 1: go.micro.service.backupAgent.HostDeleteInput
	(*HostUpdateInput)(nil), // 2: go.micro.service.backupAgent.HostUpdateInput
	(*ListItem)(nil),        // 3: go.micro.service.backupAgent.ListItem
	(*HostOneMessage)(nil),  // 4: go.micro.service.backupAgent.HostOneMessage
	(*HostListInput)(nil),   // 5: go.micro.service.backupAgent.HostListInput
	(*HostListOutPut)(nil),  // 6: go.micro.service.backupAgent.HostListOutPut
}
var file_host_proto_depIdxs = []int32{
	3, // 0: go.micro.service.backupAgent.HostListOutPut.listItem:type_name -> go.micro.service.backupAgent.ListItem
	0, // 1: go.micro.service.backupAgent.Host.AddHost:input_type -> go.micro.service.backupAgent.HostAddInput
	1, // 2: go.micro.service.backupAgent.Host.DeleteHost:input_type -> go.micro.service.backupAgent.HostDeleteInput
	2, // 3: go.micro.service.backupAgent.Host.UpdateHost:input_type -> go.micro.service.backupAgent.HostUpdateInput
	5, // 4: go.micro.service.backupAgent.Host.GetHostList:input_type -> go.micro.service.backupAgent.HostListInput
	4, // 5: go.micro.service.backupAgent.Host.AddHost:output_type -> go.micro.service.backupAgent.HostOneMessage
	4, // 6: go.micro.service.backupAgent.Host.DeleteHost:output_type -> go.micro.service.backupAgent.HostOneMessage
	4, // 7: go.micro.service.backupAgent.Host.UpdateHost:output_type -> go.micro.service.backupAgent.HostOneMessage
	6, // 8: go.micro.service.backupAgent.Host.GetHostList:output_type -> go.micro.service.backupAgent.HostListOutPut
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_host_proto_init() }
func file_host_proto_init() {
	if File_host_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_host_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostAddInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostDeleteInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostUpdateInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostOneMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostListInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostListOutPut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_host_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_proto_goTypes,
		DependencyIndexes: file_host_proto_depIdxs,
		MessageInfos:      file_host_proto_msgTypes,
	}.Build()
	File_host_proto = out.File
	file_host_proto_rawDesc = nil
	file_host_proto_goTypes = nil
	file_host_proto_depIdxs = nil
}
