// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: proto/backupAgent/bak/bak.proto

package bak

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBakInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID      int64  `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
}

func (x *StartBakInput) Reset() {
	*x = StartBakInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBakInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBakInput) ProtoMessage() {}

func (x *StartBakInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBakInput.ProtoReflect.Descriptor instead.
func (*StartBakInput) Descriptor() ([]byte, []int) {
	return file_proto_backupAgent_bak_bak_proto_rawDescGZIP(), []int{0}
}

func (x *StartBakInput) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *StartBakInput) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type StartBakByHostInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostID      int64  `protobuf:"varint,1,opt,name=HostID,proto3" json:"HostID,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
}

func (x *StartBakByHostInput) Reset() {
	*x = StartBakByHostInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBakByHostInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBakByHostInput) ProtoMessage() {}

func (x *StartBakByHostInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBakByHostInput.ProtoReflect.Descriptor instead.
func (*StartBakByHostInput) Descriptor() ([]byte, []int) {
	return file_proto_backupAgent_bak_bak_proto_rawDescGZIP(), []int{1}
}

func (x *StartBakByHostInput) GetHostID() int64 {
	if x != nil {
		return x.HostID
	}
	return 0
}

func (x *StartBakByHostInput) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type StopBakInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID      int64  `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
}

func (x *StopBakInput) Reset() {
	*x = StopBakInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBakInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBakInput) ProtoMessage() {}

func (x *StopBakInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBakInput.ProtoReflect.Descriptor instead.
func (*StopBakInput) Descriptor() ([]byte, []int) {
	return file_proto_backupAgent_bak_bak_proto_rawDescGZIP(), []int{2}
}

func (x *StopBakInput) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *StopBakInput) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type StopBakByHostInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostID      int64  `protobuf:"varint,1,opt,name=HostID,proto3" json:"HostID,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
}

func (x *StopBakByHostInput) Reset() {
	*x = StopBakByHostInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBakByHostInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBakByHostInput) ProtoMessage() {}

func (x *StopBakByHostInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBakByHostInput.ProtoReflect.Descriptor instead.
func (*StopBakByHostInput) Descriptor() ([]byte, []int) {
	return file_proto_backupAgent_bak_bak_proto_rawDescGZIP(), []int{3}
}

func (x *StopBakByHostInput) GetHostID() int64 {
	if x != nil {
		return x.HostID
	}
	return 0
}

func (x *StopBakByHostInput) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type BakOneMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"message" form:"message" uri:"message"
	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	OK bool `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *BakOneMessage) Reset() {
	*x = BakOneMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakOneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakOneMessage) ProtoMessage() {}

func (x *BakOneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backupAgent_bak_bak_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakOneMessage.ProtoReflect.Descriptor instead.
func (*BakOneMessage) Descriptor() ([]byte, []int) {
	return file_proto_backupAgent_bak_bak_proto_rawDescGZIP(), []int{4}
}

func (x *BakOneMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BakOneMessage) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

var File_proto_backupAgent_bak_bak_proto protoreflect.FileDescriptor

var file_proto_backupAgent_bak_bak_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x62, 0x61, 0x6b, 0x2f, 0x62, 0x61, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x22,
	0x49, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x61, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x0c, 0x53,
	0x74, 0x6f, 0x70, 0x42, 0x61, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x6b,
	0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x6f, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x42, 0x61, 0x6b, 0x4f, 0x6e, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b,
	0x32, 0xc0, 0x03, 0x0a, 0x0a, 0x42, 0x61, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x66, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x6b, 0x12, 0x2b, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x6b, 0x4f, 0x6e, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x42,
	0x61, 0x6b, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2b,
	0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x61,
	0x6b, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x72, 0x0a,
	0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x31, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x42, 0x61, 0x6b, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x70, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x6b, 0x42, 0x79, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x30, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x6b, 0x4f, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x42, 0x61, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_backupAgent_bak_bak_proto_rawDescOnce sync.Once
	file_proto_backupAgent_bak_bak_proto_rawDescData = file_proto_backupAgent_bak_bak_proto_rawDesc
)

func file_proto_backupAgent_bak_bak_proto_rawDescGZIP() []byte {
	file_proto_backupAgent_bak_bak_proto_rawDescOnce.Do(func() {
		file_proto_backupAgent_bak_bak_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_backupAgent_bak_bak_proto_rawDescData)
	})
	return file_proto_backupAgent_bak_bak_proto_rawDescData
}

var file_proto_backupAgent_bak_bak_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_backupAgent_bak_bak_proto_goTypes = []interface{}{
	(*StartBakInput)(nil),       // 0: go.micro.service.backupAgent.StartBakInput
	(*StartBakByHostInput)(nil), // 1: go.micro.service.backupAgent.StartBakByHostInput
	(*StopBakInput)(nil),        // 2: go.micro.service.backupAgent.StopBakInput
	(*StopBakByHostInput)(nil),  // 3: go.micro.service.backupAgent.StopBakByHostInput
	(*BakOneMessage)(nil),       // 4: go.micro.service.backupAgent.BakOneMessage
}
var file_proto_backupAgent_bak_bak_proto_depIdxs = []int32{
	0, // 0: go.micro.service.backupAgent.BakService.StartBak:input_type -> go.micro.service.backupAgent.StartBakInput
	2, // 1: go.micro.service.backupAgent.BakService.StopBak:input_type -> go.micro.service.backupAgent.StopBakInput
	1, // 2: go.micro.service.backupAgent.BakService.StartBakByHost:input_type -> go.micro.service.backupAgent.StartBakByHostInput
	3, // 3: go.micro.service.backupAgent.BakService.StopBakByHost:input_type -> go.micro.service.backupAgent.StopBakByHostInput
	4, // 4: go.micro.service.backupAgent.BakService.StartBak:output_type -> go.micro.service.backupAgent.BakOneMessage
	4, // 5: go.micro.service.backupAgent.BakService.StopBak:output_type -> go.micro.service.backupAgent.BakOneMessage
	4, // 6: go.micro.service.backupAgent.BakService.StartBakByHost:output_type -> go.micro.service.backupAgent.BakOneMessage
	4, // 7: go.micro.service.backupAgent.BakService.StopBakByHost:output_type -> go.micro.service.backupAgent.BakOneMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_backupAgent_bak_bak_proto_init() }
func file_proto_backupAgent_bak_bak_proto_init() {
	if File_proto_backupAgent_bak_bak_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_backupAgent_bak_bak_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBakInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_backupAgent_bak_bak_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBakByHostInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_backupAgent_bak_bak_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBakInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_backupAgent_bak_bak_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBakByHostInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_backupAgent_bak_bak_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakOneMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_backupAgent_bak_bak_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backupAgent_bak_bak_proto_goTypes,
		DependencyIndexes: file_proto_backupAgent_bak_bak_proto_depIdxs,
		MessageInfos:      file_proto_backupAgent_bak_bak_proto_msgTypes,
	}.Build()
	File_proto_backupAgent_bak_bak_proto = out.File
	file_proto_backupAgent_bak_bak_proto_rawDesc = nil
	file_proto_backupAgent_bak_bak_proto_goTypes = nil
	file_proto_backupAgent_bak_bak_proto_depIdxs = nil
}
